# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyzer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalyzer.proto\x12\nmalwarelab\"\xa0\x01\n\rSampleRequest\x12\x0e\n\x06sha256\x18\x01 \x01(\t\x12\x13\n\x0bsample_path\x18\x02 \x01(\t\x12\x39\n\x08metadata\x18\x03 \x03(\x0b\x32\'.malwarelab.SampleRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xfb\x02\n\x0e\x41nalysisResult\x12\x15\n\ranalyzer_name\x18\x01 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x11\n\tis_packed\x18\x04 \x01(\x08\x12\x13\n\x0bpacker_name\x18\x05 \x01(\t\x12\x19\n\x11packer_confidence\x18\x06 \x01(\x02\x12\x1b\n\x13strings_of_interest\x18\x07 \x03(\t\x12\x0f\n\x07imports\x18\x08 \x03(\t\x12\x0f\n\x07\x65xports\x18\t \x03(\t\x12\x1d\n\x04ttps\x18\n \x03(\x0b\x32\x0f.malwarelab.TTP\x12\x1c\n\x14unpacked_sample_path\x18\x0b \x01(\t\x12\x34\n\x05\x65xtra\x18\x0c \x03(\x0b\x32%.malwarelab.AnalysisResult.ExtraEntry\x12\r\n\x05\x65rror\x18\r \x01(\t\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"i\n\x03TTP\x12\x14\n\x0ctechnique_id\x18\x01 \x01(\t\x12\x16\n\x0etechnique_name\x18\x02 \x01(\t\x12\x0e\n\x06tactic\x18\x03 \x01(\t\x12\x10\n\x08\x65vidence\x18\x04 \x01(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\"d\n\x14\x43\x61pabilitiesResponse\x12\x19\n\x11supported_formats\x18\x01 \x03(\t\x12\x1b\n\x13supported_languages\x18\x02 \x03(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\"\x07\n\x05\x45mpty2\x91\x01\n\x08\x41nalyzer\x12@\n\x07\x41nalyze\x12\x19.malwarelab.SampleRequest\x1a\x1a.malwarelab.AnalysisResult\x12\x43\n\x0c\x43\x61pabilities\x12\x11.malwarelab.Empty\x1a .malwarelab.CapabilitiesResponseB,Z*malware-lab/shared/proto-gen/go;malwarelabb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*malware-lab/shared/proto-gen/go;malwarelab'
  _globals['_SAMPLEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_SAMPLEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ANALYSISRESULT_EXTRAENTRY']._loaded_options = None
  _globals['_ANALYSISRESULT_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_SAMPLEREQUEST']._serialized_start=31
  _globals['_SAMPLEREQUEST']._serialized_end=191
  _globals['_SAMPLEREQUEST_METADATAENTRY']._serialized_start=144
  _globals['_SAMPLEREQUEST_METADATAENTRY']._serialized_end=191
  _globals['_ANALYSISRESULT']._serialized_start=194
  _globals['_ANALYSISRESULT']._serialized_end=573
  _globals['_ANALYSISRESULT_EXTRAENTRY']._serialized_start=529
  _globals['_ANALYSISRESULT_EXTRAENTRY']._serialized_end=573
  _globals['_TTP']._serialized_start=575
  _globals['_TTP']._serialized_end=680
  _globals['_CAPABILITIESRESPONSE']._serialized_start=682
  _globals['_CAPABILITIESRESPONSE']._serialized_end=782
  _globals['_EMPTY']._serialized_start=784
  _globals['_EMPTY']._serialized_end=791
  _globals['_ANALYZER']._serialized_start=794
  _globals['_ANALYZER']._serialized_end=939
# @@protoc_insertion_point(module_scope)
